/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as JoinRouteImport } from './routes/join'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EnableFaceidRouteImport } from './routes/enable-faceid'
import { Route as BiometricRouteImport } from './routes/biometric'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingStepRouteImport } from './routes/onboarding.$step'
import { Route as KycRejectedRouteImport } from './routes/kyc.rejected'
import { Route as KycPendingRouteImport } from './routes/kyc.pending'
import { Route as KycApprovedRouteImport } from './routes/kyc.approved'
import { Route as KycStepRouteImport } from './routes/kyc.$step'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EnableFaceidRoute = EnableFaceidRouteImport.update({
  id: '/enable-faceid',
  path: '/enable-faceid',
  getParentRoute: () => rootRouteImport,
} as any)
const BiometricRoute = BiometricRouteImport.update({
  id: '/biometric',
  path: '/biometric',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStepRoute = OnboardingStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => OnboardingRoute,
} as any)
const KycRejectedRoute = KycRejectedRouteImport.update({
  id: '/rejected',
  path: '/rejected',
  getParentRoute: () => KycRoute,
} as any)
const KycPendingRoute = KycPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => KycRoute,
} as any)
const KycApprovedRoute = KycApprovedRouteImport.update({
  id: '/approved',
  path: '/approved',
  getParentRoute: () => KycRoute,
} as any)
const KycStepRoute = KycStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => KycRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biometric': typeof BiometricRoute
  '/enable-faceid': typeof EnableFaceidRoute
  '/home': typeof HomeRoute
  '/join': typeof JoinRoute
  '/kyc': typeof KycRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/splash': typeof SplashRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/kyc/$step': typeof KycStepRoute
  '/kyc/approved': typeof KycApprovedRoute
  '/kyc/pending': typeof KycPendingRoute
  '/kyc/rejected': typeof KycRejectedRoute
  '/onboarding/$step': typeof OnboardingStepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biometric': typeof BiometricRoute
  '/enable-faceid': typeof EnableFaceidRoute
  '/home': typeof HomeRoute
  '/join': typeof JoinRoute
  '/kyc': typeof KycRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/splash': typeof SplashRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/kyc/$step': typeof KycStepRoute
  '/kyc/approved': typeof KycApprovedRoute
  '/kyc/pending': typeof KycPendingRoute
  '/kyc/rejected': typeof KycRejectedRoute
  '/onboarding/$step': typeof OnboardingStepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biometric': typeof BiometricRoute
  '/enable-faceid': typeof EnableFaceidRoute
  '/home': typeof HomeRoute
  '/join': typeof JoinRoute
  '/kyc': typeof KycRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/splash': typeof SplashRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/kyc/$step': typeof KycStepRoute
  '/kyc/approved': typeof KycApprovedRoute
  '/kyc/pending': typeof KycPendingRoute
  '/kyc/rejected': typeof KycRejectedRoute
  '/onboarding/$step': typeof OnboardingStepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biometric'
    | '/enable-faceid'
    | '/home'
    | '/join'
    | '/kyc'
    | '/onboarding'
    | '/sign-in'
    | '/splash'
    | '/verify'
    | '/welcome'
    | '/kyc/$step'
    | '/kyc/approved'
    | '/kyc/pending'
    | '/kyc/rejected'
    | '/onboarding/$step'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biometric'
    | '/enable-faceid'
    | '/home'
    | '/join'
    | '/kyc'
    | '/onboarding'
    | '/sign-in'
    | '/splash'
    | '/verify'
    | '/welcome'
    | '/kyc/$step'
    | '/kyc/approved'
    | '/kyc/pending'
    | '/kyc/rejected'
    | '/onboarding/$step'
  id:
    | '__root__'
    | '/'
    | '/biometric'
    | '/enable-faceid'
    | '/home'
    | '/join'
    | '/kyc'
    | '/onboarding'
    | '/sign-in'
    | '/splash'
    | '/verify'
    | '/welcome'
    | '/kyc/$step'
    | '/kyc/approved'
    | '/kyc/pending'
    | '/kyc/rejected'
    | '/onboarding/$step'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiometricRoute: typeof BiometricRoute
  EnableFaceidRoute: typeof EnableFaceidRoute
  HomeRoute: typeof HomeRoute
  JoinRoute: typeof JoinRoute
  KycRoute: typeof KycRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  SignInRoute: typeof SignInRoute
  SplashRoute: typeof SplashRoute
  VerifyRoute: typeof VerifyRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enable-faceid': {
      id: '/enable-faceid'
      path: '/enable-faceid'
      fullPath: '/enable-faceid'
      preLoaderRoute: typeof EnableFaceidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biometric': {
      id: '/biometric'
      path: '/biometric'
      fullPath: '/biometric'
      preLoaderRoute: typeof BiometricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$step': {
      id: '/onboarding/$step'
      path: '/$step'
      fullPath: '/onboarding/$step'
      preLoaderRoute: typeof OnboardingStepRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/kyc/rejected': {
      id: '/kyc/rejected'
      path: '/rejected'
      fullPath: '/kyc/rejected'
      preLoaderRoute: typeof KycRejectedRouteImport
      parentRoute: typeof KycRoute
    }
    '/kyc/pending': {
      id: '/kyc/pending'
      path: '/pending'
      fullPath: '/kyc/pending'
      preLoaderRoute: typeof KycPendingRouteImport
      parentRoute: typeof KycRoute
    }
    '/kyc/approved': {
      id: '/kyc/approved'
      path: '/approved'
      fullPath: '/kyc/approved'
      preLoaderRoute: typeof KycApprovedRouteImport
      parentRoute: typeof KycRoute
    }
    '/kyc/$step': {
      id: '/kyc/$step'
      path: '/$step'
      fullPath: '/kyc/$step'
      preLoaderRoute: typeof KycStepRouteImport
      parentRoute: typeof KycRoute
    }
  }
}

interface KycRouteChildren {
  KycStepRoute: typeof KycStepRoute
  KycApprovedRoute: typeof KycApprovedRoute
  KycPendingRoute: typeof KycPendingRoute
  KycRejectedRoute: typeof KycRejectedRoute
}

const KycRouteChildren: KycRouteChildren = {
  KycStepRoute: KycStepRoute,
  KycApprovedRoute: KycApprovedRoute,
  KycPendingRoute: KycPendingRoute,
  KycRejectedRoute: KycRejectedRoute,
}

const KycRouteWithChildren = KycRoute._addFileChildren(KycRouteChildren)

interface OnboardingRouteChildren {
  OnboardingStepRoute: typeof OnboardingStepRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingStepRoute: OnboardingStepRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiometricRoute: BiometricRoute,
  EnableFaceidRoute: EnableFaceidRoute,
  HomeRoute: HomeRoute,
  JoinRoute: JoinRoute,
  KycRoute: KycRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  SignInRoute: SignInRoute,
  SplashRoute: SplashRoute,
  VerifyRoute: VerifyRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
